name: CI
on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master
env:
  AWS-DEFAULT-REGION: us-east-2
  SITE-BRANCH: site

jobs:
  build:
  # In this phase, the code is pulled from master and the site rendered in hugo. The built site is stored as an artifact for other stages.
    runs-on: ubuntu-18.04
    steps:
    # Check out master branch from the repo.
    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
        ref: master
    # Ensure the site succeeds Hugo builds. If it fails for some reason, the pipeline will halt.
    - name: Build site with Hugo
      uses: lowply/build-hugo@v0.69.0
    # If build succeeds, store the public/ dir as an artifact to be used in subsequent phases.
    - name: Upload output public dir as artifact
      uses: actions/upload-artifact@v1
      with:
        name: public
        path: public/
  publish:
  # In the publish phase, the site is pushed up to a different branch called "site" and also delta synchronized to the S3 bucket.
    runs-on: ubuntu-18.04
    needs: build
    steps:
    # We check out the "site" branch this time since we have to ultimately commit those changes there.
    - name: Checkout site branch
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
        ref: $SITE-BRANCH
    # Download the artifact containing the newly built site. This overwrites the public/ dir from the check out above.
    - name: Download artifact from build stage
      uses: actions/download-artifact@v1
      with:
        name: public
    # Add all the files/changes in public/ that were pulled down from the build stage and then commit them.
    - name: Commit all files in public
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A public/
        git commit -m "Publish neonmirrors to site" -a
    # Push those changes back to the "site" branch.
    - name: Push to site branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: $SITE-BRANCH
    # Since we're about to connect to AWS, we need to store the credentials on the runner.
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: $AWS-DEFAULT-REGION
    # Now we can connect, we use s5cmd to perform only a delta sync to the S3 bucket. This minimizes transfer traffic since it only uploads changed files.
    - name: Delta sync site to S3 bucket
      run: |
        curl -sLO https://github.com/peak/s5cmd/releases/download/v1.0.0/s5cmd_1.0.0_Linux-64bit.tar.gz
        tar -xzf s5cmd_1.0.0_Linux-64bit.tar.gz
        chmod +x s5cmd
        sudo mv s5cmd /usr/local/bin/
        echo "****Showing working dir and listing files.****"
        pwd && ls -lah
        echo "****Running delta sync against S3.****"
        s5cmd cp -s public/ s3://${{ secrets.AWS_S3_BUCKET_NAME }}
  invalidate:
  # In the invalidate phase, now the site has been uploaded to S3, we need to invalidate the CloudFront cache so the new site gets picked up and available to users.
    runs-on: ubuntu-18.04
    needs:
      - build
      - publish
    steps:
      # Like in the publish phase, since we're about to connect to AWS we need to store our creds.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $AWS-DEFAULT-REGION
        # Use the aws cli tool to perform a glob invalidation of the entire site against CloudFront.
      # - name: Invalidate cache on CloudFront
      #   run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRO_ID }} --paths "/*"