name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
        ref: master
    # Ensure the site succeeds Hugo builds.
    - name: Build site with Hugo
      uses: lowply/build-hugo@v0.69.0
    - name: List files in "public"
      run: |
        ls -lah public/post/2020-04/
    - name: Upload public dir as artifact
      uses: actions/upload-artifact@v1
      with:
        name: public
        path: public/
  publish:
    runs-on: ubuntu-18.04
    needs: build
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
        ref: site
    - name: Download newly generated site in public
      uses: actions/download-artifact@v1
      with:
        name: public
    - name: List files
      run: |
        sudo apt-get install tree -y
        tree public/
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A public/
        git commit -m "Publish neonmirrors to site" -a
    - name: Push to site
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: site
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Sync public to S3 bucket
      run: |
        curl -sLO https://github.com/peak/s5cmd/releases/download/v1.0.0/s5cmd_1.0.0_Linux-64bit.tar.gz
        tar -xzf s5cmd_1.0.0_Linux-64bit.tar.gz
        chmod +x s5cmd
        sudo mv s5cmd /usr/local/bin/
        echo "Showing working dir and listing files."
        pwd && ls -lah
        echo "Running delta sync against S3."
        s5cmd cp -s public/ s3://czdevtest
    # - name: publish to S3 bucket
    #   run: aws s3 ls
  invalidate:
    runs-on: ubuntu-18.04
    needs:
      - build
      - publish
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      # - name: Invalidate cache on CloudFront for root
      #   run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRO_ID }} --paths "/*"