name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    # - name: Setup Hugo
    #   uses: peaceiris/actions-hugo@v2
    #   with:
    #     hugo-version: '0.68.3'
    #     extended: true
    # Ensure the site succeeds Hugo builds.
    - name: Build Hugo
      uses: lowply/build-hugo@v0.69.0
  publish:
    runs-on: ubuntu-18.04
    needs: build
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: publish to S3 bucket
      run: aws s3 ls
  invalidate:
    runs-on: ubuntu-18.04
    needs:
      - build
      - publish
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: invalidate cache on CloudFront
        run: echo "Invalidating cache"